elasticsearch:
  image: elasticsearch:5.6.6
  command: elasticsearch
  environment:
    - network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  ports:
    - "5000:5000"
  links:
    - elasticsearch
    - rabbitmq
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
rabbitmq:
  build: rabbitmq/
  ports:
    - "5672:5672"
    - "15672:15672"
